#! /bin/sh
killall polybar
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_radius		14
bspc config border_width         3
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a vivaldi-stable state=gapless_monocle
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
#Batman Colors
bspc config focused_border_color        "#B71C1C"
bspc config normal_border_color         "#212121"
bspc config active_border_color         "#212121"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
#~/.config/polybar/launch.sh &
sh ~/.config/polybar/gotham/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
# nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom
picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Feh
#while true ; do feh --bg-scale --randomize "$HOME"/Pictures/Wallpapers/ ; sleep 300 ; done &
feh --bg-scale --randomize "$HOME"/Pictures/Wallpapers/ &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# Discord
discord --start-minimized

